server:
  port: 8090

spring:
  application:
    name: com-spider
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spider
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spider.mapper